spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE #MVCC=TRUE는 여러개를 조금 더 빠른처리를 도와주는 옵션?
    username: sa
    password:
    driver-class-name: org.h2.Driver
                                     #DB셋팅 완료
  jpa:
    hibernate:
      ddl-auto: create #자동으로 테이블 만들어주는 모드
    properties:   #hibernate에 관련한 속성을 설정
      hibernate:
        #show_sql: true (sysout으로 찍음)
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #jpa,hibernate가 생성하는 모든 sql이 다보임 (로그로 찍음)
    org.hibernate.type : trace #sql문에 어떤값이 들어갔는지 찍어줌
